export const symptomsList = [
	'Chest pain',
	'Back pain that is severe, sharp, with a ripping or tearing quality',
	'Cough',
	'Leg swelling',
	'Vomiting',
	'Blue color in the skin, lips, and nail beds',
	'A pressing, squeezing, or crushing pain, usually in the chest under your breastbone',
	'Pain that may also occur in your upper back, both arms, neck, or ear lobes',
	'Chest pain that spreads to your arms, shoulders, jaw, neck, or back',
	'Shortness of breath',
	'Weakness',
	'Extreme tiredness (fatigue)',
	'Feeling faint',
];

export const diseasesOptions = [
	'Abdominal aortic aneurysm',
	'Achilles tendinopathy',
	'Acne',
	'Acute cholecystitis',
	'Acute lymphoblastic leukaemia',
	'Acute myeloid leukaemia',
	'Acute pancreatitis',
	'Addison’s disease',
	'Adenomyosis',
	'Alcohol-related liver disease',
	'Allergic rhinitis',
	'Allergies',
	'Alzheimer’s disease',
	'Anal cancer',
	'Anaphylaxis',
	'Angina',
	'Angioedema',
	'Ankle sprain',
	'Ankle avulsion fracture',
	'Ankylosing spondylitis',
	'Anorexia nervosa',
	'Anxiety',
	'Anxiety disorders in children',
	'Appendicitis',
	'Arterial thrombosis',
	'Arthritis',
	'Asbestosis',
	'Asthma',
	'Ataxia',
	'Atopic eczema',
	'Atrial fibrillation',
	'Attention deficit hyperactivity disorder (ADHD)',
	'Autism',
	'Bacterial vaginosis',
	'Benign prostate enlargement',
	'Bile duct cancer (cholangiocarcinoma)',
	'Binge eating',
	'Bipolar disorder',
	'Bladder cancer',
	'Blood poisoning (sepsis)',
	'Bone cancer',
	'Bone cancer: Teenagers and young adults',
	'Bowel cancer',
	'Bowel incontinence',
	'Bowel polyps',
	'Brain stem death',
	'Brain tumours',
	'Brain tumours: Children',
	'Brain tumours: Teenagers and young adults',
	'Breast cancer (female)',
	'Breast cancer (male)',
	'Bronchiectasis',
	'Bronchitis',
	'Bulimia',
	'Bunion',
	'Carcinoid syndrome and carcinoid tumours',
	'Cardiovascular disease',
	'Carpal tunnel syndrome',
	'Catarrh',
	'Cellulitis',
	'Cerebral palsy',
	'Cervical cancer',
	'Cervical spondylosis',
	'Chest and rib injury',
	'Chest infection',
	'Chickenpox',
	'Chilblains',
	'Chlamydia',
	'Chronic fatigue syndrome',
	'Chronic kidney disease',
	'Chronic lymphocytic leukaemia',
	'Chronic myeloid leukaemia',
	'Chronic obstructive pulmonary disease (COPD)',
	'Chronic pain',
	'Chronic pancreatitis',
	'Cirrhosis',
	'Clostridium difficile',
	'Coeliac disease',
	'Cold sore',
	'Coma',
	'Common cold',
	'Concussion',
	'Congenital heart disease',
	'Conjunctivitis',
	'Constipation',
	'Coronary heart disease',
	'Coronavirus (COVID-19)',
	'Coronavirus (COVID-19): Longer-term effects (long COVID)',
	'Costochondritis',
	'Cough',
	'Crohn’s disease',
	'Croup',
	'Cystic fibrosis',
	'Cystitis',
	'Deep vein thrombosis',
	'Degenerative cervical myelopathy',
	'Dehydration',
	'Delirium',
	'Dementia',
	'Dental abscess',
	'Depression',
	'Dermatitis herpetiformis',
	'Diabetes',
	'Diabetic retinopathy',
	'Diarrhoea',
	'Discoid eczema',
	'Diverticular disease and diverticulitis',
	'Dizziness (Lightheadedness)',
	'Down’s syndrome',
	'Dry mouth',
	'Dysphagia (swallowing problems)',
	'Dystonia',
	'Earache',
	'Earwax build-up',
	'Ebola virus disease',
	'Ectopic pregnancy',
	'Edwards’ syndrome',
	'Endometriosis',
	'Epilepsy',
	'Erectile dysfunction (impotence)',
	'Escherichia coli (E. coli) O157',
	'Ewing sarcoma',
	'Ewing sarcoma: Children',
	'Eye cancer',
	'Eating disorders',
	'Febrile seizures',
	'Feeling of something in your throat (Globus)',
	'Fibroids',
	'Fibromyalgia',
	'Flu',
	'Food allergy',
	'Food poisoning',
	'Fragility fracture of the hip',
	'Frozen shoulder',
	'Functional neurological disorder (FND)',
	'Fungal nail infection',
	'Gallbladder cancer',
	'Gallstones',
	'Ganglion cyst',
	'Gastroenteritis',
	'Gastro-oesophageal reflux disease (GORD)',
	'Genital herpes',
	'Genital symptoms',
	'Genital warts',
	'Germ cell tumours',
	'Glandular fever',
	'Golfers elbow',
	'Gonorrhoea',
	'Gout',
	'Greater trochanteric pain syndrome',
	'Gum disease',
	'Haemorrhoids (piles)',
	'Hand, foot and mouth disease',
	'Hay fever',
	'Head and neck cancer',
	'Head lice and nits',
	'Headaches',
	'Hearing loss',
	'Heart attack',
	'Heart block',
	'Heart failure',
	'Heart palpitations',
	'Hepatitis A',
	'Hepatitis B',
	'Hepatitis C',
	'Hiatus hernia',
	'High blood pressure (hypertension)',
	'High cholesterol',
	'HIV',
	'Hives',
	'Hodgkin lymphoma',
	'Hodgkin lymphoma: Children',
	'Hodgkin lymphoma: Teenagers and young adults',
	'Huntington’s disease',
	'Hydrocephalus',
	'Hyperglycaemia (high blood sugar)',
	'Hyperhidrosis',
	'Hypoglycaemia (low blood sugar)',
	'Idiopathic pulmonary fibrosis',
	'Impetigo',
	'Indigestion',
	'Ingrown toenail',
	'Infertility',
	'Inflammatory bowel disease (IBD)',
	'Inherited heart conditions',
	'Insomnia',
	'Iron deficiency anaemia',
	'Irritable bowel syndrome (IBS)',
	'Itching',
	'Itchy bottom',
	'Itchy skin',
	'Joint hypermobility',
	'Kaposi’s sarcoma',
	'Kidney cancer',
	'Kidney infection',
	'Kidney stones',
	'Labyrinthitis',
	'Lactose intolerance',
	'Laryngeal (larynx) cancer',
	'Laryngitis',
	'Leg cramps',
	'Lichen planus',
	'Lipoedema',
	'Liver cancer',
	'Liver disease',
	'Liver tumours',
	'Long-term effects of COVID-19',
	'Loss of libido',
	'Low blood pressure (hypotension)',
	'Lumbar stenosis',
	'Lung cancer',
	'Lupus',
	'Lyme disease',
	'Lymphoedema',
	'Lymphogranuloma venereum (LGV)',
	'Malaria',
	'Malignant brain tumour (cancerous)',
	'Malnutrition',
	'Managing genital symptoms',
	'Measles',
	'Meningitis',
	'Meniere’s disease',
	'Menopause',
	'Mesothelioma',
	'Middle ear infection (otitis media)',
	'Migraine',
	'Minor head injury',
	'Miscarriage',
	'Motor neurone disease (MND)',
	'Mouth cancer',
	'Mouth ulcer',
	'Multiple myeloma',
	'Multiple sclerosis (MS)',
	'Multiple system atrophy (MSA)',
	'Mumps',
	'Munchausen’s syndrome',
	'Muscular dystrophy',
	'Myalgic encephalomyelitis (ME) or chronic fatigue syndrome (CFS)',
	'Myasthenia gravis',
	'Nasal and sinus cancer',
	'Nasopharyngeal cancer',
	'Neck problems',
	'Neuroblastoma: Children',
	'Neuroendocrine tumours',
	'Non-alcoholic fatty liver disease (NAFLD)',
	'Non-Hodgkin lymphoma',
	'Non-Hodgkin lymphoma: Children',
	'Norovirus',
	'Nosebleed',
	'Obesity',
	'Obsessive compulsive disorder (OCD)',
	'Obstructive sleep apnoea',
	'Oesophageal cancer',
	'Oral thrush in adults',
	'Osteoarthritis',
	'Osteoarthritis of the hip',
	'Osteoarthritis of the knee',
	'Osteoarthritis of the thumb',
	'Osteoporosis',
	'Osteosarcoma',
	'Outer ear infection (otitis externa)',
	'Ovarian cancer',
	'Ovarian cancer: Teenagers and young adults',
	'Ovarian cyst',
	'Overactive thyroid',
	'Pain in the ball of the foot',
	'Paget’s disease of the nipple',
	'Pancreatic cancer',
	'Panic disorder',
	'Parkinson’s disease',
	'Patau’s syndrome',
	'Patellofemoral pain syndrome',
	'Pelvic inflammatory disease (PID)',
	'Peptic ulcer disease',
	'Peripheral neuropathy',
	'Peritonitis',
	'Perthes’ disease',
	'Phantom limb pain',
	'Pilonidal sinus',
	'Pituitary tumours',
	'Pneumonia',
	'Polio',
	'Polyarteritis nodosa',
	'Polycystic ovary syndrome (PCOS)',
	'Postnatal depression',
	'Post-traumatic stress disorder (PTSD)',
	'Postural tachycardia syndrome',
	'Prostate cancer',
	'Prostate problems',
	'Pseudotumor cerebri',
	'Psoriasis',
	'Pulmonary embolism',
	'Pulmonary fibrosis',
	'Rashes',
	'Raynaud’s disease',
	'Reflux',
	'Repetitive strain injury (RSI)',
	'Restless legs syndrome',
	'Rheumatic fever',
	'Rheumatoid arthritis',
	'Rubella',
	'Salmonella',
	'Sciatica',
	'Scoliosis',
	'Septic arthritis',
	'Shingles',
	'Sinusitis',
	'Skin cancer',
	'Sleep apnoea',
	'Sleep problems in children',
	'Sore throat',
	'Spondylitis',
	'Spondylosis',
	'Sprains and strains',
	'Squamous cell carcinoma',
	'Stomach cancer',
	'Stomach cramps',
	'Stomach ulcers',
	'Stroke',
	'Stye',
	'Subarachnoid haemorrhage',
	'Suicide',
	'Superficial thrombophlebitis',
	'Swallowing problems',
	'Swine flu',
	'Tachycardia',
	'Testicular cancer',
	'Testicular pain',
	'Throat cancer',
	'Throat infection',
	'Thyroid cancer',
	'Thyroid problems',
	'Tinnitus',
	'Tooth abscess',
	'Tooth decay',
	'Toxic shock syndrome',
	'Tonsillitis',
	'Torticollis',
	'Trauma',
	'Trigeminal neuralgia',
	'Tuberculosis (TB)',
	'Ulcerative colitis',
	'Urinary retention',
	'Urinary tract infection (UTI)',
	'Urticaria (hives)',
	'Vaginal cancer',
	'Vaginal discharge',
	'Vaginal dryness',
	'Vaginal prolapse',
	'Varicose veins',
	'Vasectomy',
	'Vertebral fracture',
	'Viral infection',
	'Viral tonsillitis',
	'Vitamin D deficiency',
	'Warts',
	'Whiplash',
	'Wilson’s disease',
	'Worms (parasites)',
	'Wrist sprain',
];

