const data = {
	id: 'simple/1',
	number: 1,
	name: 'Simple Crossword #1',
	date: 1542326400000,
	entries: [
		{
			id: '1-across',
			number: 1,
			humanNumber: '1',
			clue: 'This helps the body regulate many important functions: temperature, blood pressure, nutrient concentration, nutrient transportation',
			direction: 'across',
			length: 5,
			group: ['1-across'],
			position: { x: 0, y: 8 },
			separatorLocations: {},
			solution: 'WATER',
		},
		{
			id: '2-across',
			number: 2,
			humanNumber: '2',
			clue: 'One of the keys to top athletic performance',
			direction: 'across',
			length: 9,
			group: ['2-across'],
			position: { x: 3, y: 9 },
			separatorLocations: {},
			solution: 'NUTRITION',
		},
		{
			id: '3-down',
			number: 3,
			humanNumber: '3',
			clue: 'Athletes should consume their last meal 2-4 hours before a training or competition unless they have this type of stomach then 4 hours before',
			direction: 'down',
			length: 9,
			group: ['3-down'],
			position: { x: 7, y: 5 },
			separatorLocations: {},
			solution: 'SENSITIVE',
		},
		{
			id: '4-down',
			number: 4,
			humanNumber: '4',
			clue: "55 to 60 percent of an athlete's calories should come from this",
			direction: 'down',
			length: 12,
			group: ['4-down'],
			position: { x: 1, y: 7 },
			separatorLocations: {},
			solution: 'CARBOHYDRATE',
		},
		{
			id: '5-across',
			number: 5,
			humanNumber: '5',
			clue: 'Good during event/exercise food',
			direction: 'across',
			length: 6,
			group: ['5-across'],
			position: { x: 5, y: 7 },
			separatorLocations: {},
			solution: 'BANANA',
		},
		{
			id: '6-across',
			number: 6,
			humanNumber: '6',
			clue: 'Muscles tend to do this when they are dehydrated',
			direction: 'across',
			length: 5,
			group: ['6-across'],
			position: { x: 9, y: 3 },
			separatorLocations: {},
			solution: 'CRAMP',
		},
		{
			id: '7-down',
			number: 7,
			humanNumber: '7',
			clue: 'The kind of diet athletes should eat',
			direction: 'down',
			length: 13,
			group: ['7-down'],
			position: { x: 3, y: 3 },
			separatorLocations: {},
			solution: 'NUTRIENTDENSE',
		},
		{
			id: '8-down',
			number: 8,
			humanNumber: '8',
			clue: 'This is how carbohydrates are stored in the liver and muscle to fuel working muscles',
			direction: 'down',
			length: 8,
			group: ['8-down'],
			position: { x: 9, y: 0 },
			separatorLocations: {},
			solution: 'GLYCOGEN',
		},
		{
			id: '9-across',
			number: 9,
			humanNumber: '9',
			clue: 'How often in minutes should athletes drink water during an event',
			direction: 'across',
			length: 7,
			group: ['9-across'],
			position: { x: 6, y: 11 },
			separatorLocations: {},
			solution: 'FIFTEEN',
		},
	],
	solutionAvailable: true,
	dateSolutionAvailable: 1542326400000,
	dimensions: { cols: 14, rows: 19 },
	crosswordType: 'quick',
};
export default data;
