const data = {
  id: 'simple/1',
  number: 1,
  name: 'Simple Crossword #1',
  date: 1542326400000,
  entries: [
    {
      id: '1-across',
      number: 1,
      humanNumber: '1',
      clue: 'This helps the body regulate many important functions: temperature, blood pressure, nutrient concentration, nutrient transportation',
      direction: 'across',
      length: 5,
      group: ['1-across'],
      position: { x: 0, y: 14 },
      separatorLocations: {},
      solution: 'WATER',
    },
    {
      id: '2-down',
      number: 2,
      humanNumber: '2',
      clue: 'Good post-event/exercise food',
      direction: 'down',
      length: 14,
      group: ['2-down'],
      position: { x: 1, y: 7 },
      separatorLocations: {},
      solution: 'TURKEYSANDWICH',
    },
    {
      id: '3-down',
      number: 3,
      humanNumber: '3',
      clue: 'How you should eat protein and fat during exercise',
      direction: 'down',
      length: 9,
      group: ['3-down'],
      position: { x: 4, y: 11 },
      separatorLocations: {},
      solution: 'SPARINGLY',
    },
    {
      id: '4-across',
      number: 4,
      humanNumber: '4',
      clue: 'One of the keys to top athletic performance',
      direction: 'across',
      length: 9,
      group: ['4-across'],
      position: { x: 4, y: 16 },
      separatorLocations: {},
      solution: 'NUTRITION',
    },
    {
      id: '5-down',
      number: 5,
      humanNumber: '5',
      clue: 'Essential building block of the body for growing muscles and body function',
      direction: 'down',
      length: 7,
      group: ['5-down'],
      position: { x: 6, y: 13 },
      separatorLocations: {},
      solution: 'PROTEIN',
    },
    {
      id: '6-down',
      number: 6,
      humanNumber: '6',
      clue: "Athletes should consume their last meal 2-4 hours before a training or competition unless they have this type of stomach then 4 hours before",
      direction: 'down',
      length: 9,
      group: ['6-down'],
      position: { x: 8, y: 12 },
      separatorLocations: {},
      solution: 'SENSITIVE',
    },
    {
      id: '7-down',
      number: 7,
      humanNumber: '7',
      clue: 'A good choice if exercising over 45 minutes',
      direction: 'down',
      length: 11,
      group: ['7-down'],
      position: { x: 10, y: 8 },
      separatorLocations: {},
      solution: 'SPORTSDRINK',
    },
    {
      id: '8-across',
      number: 8,
      humanNumber: '8',
      clue: "55 to 60 percent of an athlete's calories should come from this",
      direction: 'across',
      length: 12,
      group: ['8-across'],
      position: { x: 6, y: 10 },
      separatorLocations: {},
      solution: 'CARBOHYDRATE',
    },
    {
      id: '9-across',
      number: 9,
      humanNumber: '9',
      clue: "Athletes should drink water before, during and after an event even if they don't feel",
      direction: 'across',
      length: 7,
      group: ['9-across'],
      position: { x: 6, y: 8 },
      separatorLocations: {},
      solution: 'THIRSTY',
    },
    {
      id: '10-down',
      number: 10,
      humanNumber: '10',
      clue: "20 to 25 percent of an athlete's calories should come from this",
      direction: 'down',
      length: 3,
      group: ['10-down'],
      position: { x: 6, y: 6 },
      separatorLocations: {},
      solution: 'FAT',
    },
    {
      id: '11-down',
      number: 11,
      humanNumber: '11',
      clue: 'Drinking too much water can alter this and cause body harm',
      direction: 'down',
      length: 12,
      group: ['11-down'],
      position: { x: 14, y: 5 },
      separatorLocations: {},
      solution: 'ELECTROLYTES',
    },


    {
      id: '12-across',
      number: 12,
      humanNumber: '12',
      clue: 'Color of your urine if not dehydrated',
      direction: 'across',
      length: 10,
      group: ['12-across'],
      position: { x: 8, y: 6 },
      separatorLocations: {},
      solution: 'PALEYELLOW',
    },
    {
      id: '13-down',
      number: 13,
      humanNumber: '13',
      clue: 'Good during event/exercise food',
      direction: 'down',
      length: 6,
      group: ['13-down'],
      position: { x: 9, y: 1 },
      separatorLocations: {},
      solution: 'BANANA',
    },
    {
      id: '14-across',
      number: 14,
      humanNumber: '14',
      clue: 'The last meal before a competition or intense exercise should include a moderate amount of protein, low fat and',
      direction: 'across',
      length: 5,
      group: ['14-across'],
      position: { x: 7, y: 1 },
      separatorLocations: {},
      solution: 'FIBER',
    },
    {
      id: '15-down',
      number: 15,
      humanNumber: '15',
      clue: 'Muscles tend to do this when they are dehydrated',
      direction: 'down',
      length: 5,
      group: ['15-down'],
      position: { x: 11, y: 0 },
      separatorLocations: {},
      solution: 'CRAMP',
    },
    {
      id: '16-down',
      number: 16,
      humanNumber: '16',
      clue: 'How many hours should a meal and fluid be eaten after exercise and consist of mostly carbohydrates, lean protein and low fat',
      direction: 'down',
      length: 3,
      group: ['16-down'],
      position: { x: 16, y: 4 },
      separatorLocations: {},
      solution: 'TWO',
    },
    {
      id: '17-across',
      number: 17,
      humanNumber: '17',
      clue: 'The first stage in recovery that should start within 15-60 minutes after exercise and consist of carbohydrate and 10-15 grams of protein',
      direction: 'across',
      length: 13,
      group: ['17-across'],
      position: { x: 14, y: 16 },
      separatorLocations: {},
      solution: 'SNACKANDFLUID',
    },
    {
      id: '18-down',
      number: 18,
      humanNumber: '18',
      clue: 'Nutrient that provides energy during exercise',
      direction: 'down',
      length: 13,
      group: ['18-down'],
      position: { x: 19, y: 7 },
      separatorLocations: {},
      solution: 'CARBOHYDRATES',
    },
    {
      id: '19-down',
      number: 19,
      humanNumber: '19',
      clue: 'The kind of diet athletes should eat',
      direction: 'down',
      length: 13,
      group: ['19-down'],
      position: { x: 21, y: 8 },
      separatorLocations: {},
      solution: 'NUTRIENTDENSE',
    },
    {
      id: '20-across',
      number: 20,
      humanNumber: '20',
      clue: 'Good pre-event/exercise food',
      direction: 'across',
      length: 20,
      group: ['20-across'],
      position: { x: 18, y: 18 },
      separatorLocations: {},
      solution: 'PEANUTBUTTERANDJELLY',
    },
    {
      id: '21-down',
      number: 21,
      humanNumber: '21',
      clue: 'This is how carbohydrates are stored in the liver and muscle to fuel working muscles',
      direction: 'down',
      length: 8,
      group: ['21-down'],
      position: { x: 28, y: 12 },
      separatorLocations: {},
      solution: 'GLYCOGEN',
    },

    {
      id: '22-across',
      number: 22,
      humanNumber: '22',
      clue: 'The last meal before a competition or intense exercise should come from this type of carbohydrate',
      direction: 'across',
      length: 7,
      group: ['22-across'],
      position: { x: 24, y: 13 },
      separatorLocations: {},
      solution: 'COMPLEX',
    },
    {
      id: '23-down',
      number: 23,
      humanNumber: '23',
      clue: 'What stage of recovery is eating a snack and fluid within 4 hours after exercise and consist of carbohydrate and 10-15 grams of protein',
      direction: 'down',
      length: 5,
      group: ['23-down'],
      position: { x: 32, y: 14 },
      separatorLocations: {},
      solution: 'THIRD',
    },
    {
      id: '24-down',
      number: 24,
      humanNumber: '24',
      clue: 'How often in minutes should athletes drink water during an event',
      direction: 'down',
      length: 7,
      group: ['24-down'],
      position: { x: 34, y: 14 },
      separatorLocations: {},
      solution: 'FIFTEEN',
    },
  ],
  solutionAvailable: true,
  dateSolutionAvailable: 1542326400000,
  dimensions: { cols: 38, rows: 21 },
  crosswordType: 'quick',
};
export default data;